### ISSUE TITLE
Solito with nativewind starter does not work

### ISSUE THREAD

**Issue by smachi** [gluestack/gluestack-ui-head-starter-kits#2]
Just installing dependencies and running `yarn web` it throws and error when opening in a browser:

```
../../node_modules/react-native-css-interop/dist/doctor.js
Module parse failed: Unexpected token (13:11)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| }
| function verifyJSX() {
>     return <react-native-css-interop-jsx-pragma-check /> === true;
| }
| exports.verifyJSX = verifyJSX;
```

And `yarn native` also throws an error:

```
Development build: Unable to get the default URI scheme for the project. Please make sure the expo-dev-client package is installed.
Starting project at /solito-with-nativewind/apps/expo
Error: Cannot find module '/solito-with-nativewind/apps/expo/tailwind.config.js'
Require stack:
- /solito-with-nativewind/node_modules/tailwindcss/lib/lib/load-config.js
Error: Cannot find module '/solito-with-nativewind/apps/expo/tailwind.config.js'
Require stack:
- /solito-with-nativewind/node_modules/tailwindcss/lib/lib/load-config.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Function.resolve (node:internal/modules/helpers:187:19)
    at _resolve (/solito-with-nativewind/node_modules/jiti/dist/jiti.js:1:251148)
    at jiti (/solito-with-nativewind/node_modules/jiti/dist/jiti.js:1:253746)
    at /solito-with-nativewind/node_modules/tailwindcss/lib/lib/load-config.js:52:30
    at loadConfig (/solito-with-nativewind/node_modules/tailwindcss/lib/lib/load-config.js:54:6)
    at getTailwindConfig (/solito-with-nativewind/node_modules/nativewind/dist/metro/index.js:91:45)
    at withNativeWind (/solito-with-nativewind/node_modules/nativewind/dist/metro/index.js:23:27)
    at Object.<anonymous> (/solito-with-nativewind/apps/expo/metro.config.js:31:18)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
```

For the native error, I've tried to copy the tailwind.config.js into the expo directory and it runs, but throws a new error afterwards:

```
Failed to construct transformer:  DuplicateError: Duplicated files or mocks. Please check the console for more info
    at setModule (/solito-with-nativewind/node_modules/metro-file-map/src/index.js:456:17)
    at workerReply (/solito-with-nativewind/node_modules/metro-file-map/src/index.js:513:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 1412)
    at async HasteMap._applyFileDelta (/solito-with-nativewind/node_modules/metro-file-map/src/index.js:678:7)
    at async /solito-with-nativewind/node_modules/metro-file-map/src/index.js:333:9
    at async DependencyGraph.ready (/solito-with-nativewind/node_modules/metro/src/node-haste/DependencyGraph.js:95:5)
    at async Bundler.ready (/solito-with-nativewind/node_modules/metro/src/Bundler.js:69:5)
    at async IncrementalBundler.ready (/solito-with-nativewind/node_modules/metro/src/IncrementalBundler.js:289:5)
    at async Server.ready (/solito-with-nativewind/node_modules/metro/src/Server.js:1085:5) {
  mockPath1: 'package.json',
  mockPath2: '../../expo/package.json
```

**Comment by cglacet** [comment]
Did you find a solution to this?
